@base = {{baseUrl}}/physicians

### get physicians
GET {{base}}
Accept: application/json
#  Authorization: Bearer {{token}}

### Create physician
POST {{base}}
Content-Type: application/json

{
  "name": "Jose S Reyes",
  "email": "josesreyes@email.com",
  "document": "fgd12341",
  "specialty": "PEDIATRÍA",
  "address": {
    "street": "street 01",
    "number": "1",
    "complement": "My complement",
    "barrio": "Bosque de las Lomas",
    "zipCode": "123412",
    "city": "Mexico City",
    "state": "CDMX"
  }
}

### Update physician
PUT {{base}}/1
Content-Type: application/json

{
  "name": "José Sánchez",
  "email": "jose.sanchez@example.com"
}

### Eliminar usuario
DELETE {{base}}/1